### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/fluxbb_ynh#4]
Your app is currently failing all tests on our CI.
https://ci-apps.yunohost.org/ci/job/2340

Unless the app is fixed before next Saturday, 13th, this app will be set at notworking.

**Comment by anto1ne** [comment]
HI,

this app should have a higher level once PR  https://github.com/YunoHost-Apps/fluxbb_ynh/pull/3 is merget

**Comment by anto1ne** [comment]
the app is know level 7
